Traceback (most recent call last):
  File "main.py", line 36, in <module>
    history = fit(epochs, net, train_ds, val_ds, device, opt = optimizer)
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 102, in fit
    wandb.log({"Evaluation result": result, "Loss": mean(losses)})
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/statistics.py", line 316, in mean
    T, total, count = _sum(data)
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/statistics.py", line 166, in _sum
    for n,d in map(_exact_ratio, values):
  File "/home/jeffreymo572/anaconda3/envs/Kaggles/lib/python3.8/statistics.py", line 248, in _exact_ratio
    raise TypeError(msg.format(type(x).__name__))
TypeError: can't convert type 'Tensor' to numerator/denominator