Traceback (most recent call last):
  File "main.py", line 45, in <module>
    history = fit(epochs, net, train_ds, val_ds, device, opt = optimizer)
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 124, in fit
    # Validation phase
  File "/home/jeffreymo572/Kaggles/common/utils.py", line 104, in evaluate
    outputs.append(model.validation_step((x,y)))
  File "/home/jeffreymo572/Kaggles/common/NeuralNets.py", line 155, in validation_epoch_end
    batch_accuracy = [a['accuracy'] for a in outputs]
  File "/home/jeffreymo572/Kaggles/common/NeuralNets.py", line 155, in <listcomp>
    batch_accuracy = [a['accuracy'] for a in outputs]
KeyError: 'accuracy'