Traceback (most recent call last):
  File "main.py", line 25, in <module>
    df = df.drop(['id']) # Drop id
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/jeffreymo572/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['id'] not found in axis"